import type { Calendar } from "@life-calendar/common";
import type React from "react";
import { useState } from "react";
import { createCalendar } from "../calendarAPI";

interface CreateCalendarProps {
  setCurrentCalendar: (calendar: Calendar | null) => void;
  onBackClick: () => void;
}

const CreateCalendar: React.FC<CreateCalendarProps> = ({
  setCurrentCalendar,
  onBackClick,
}) => {
  const [formData, setFormData] = useState({
    name: "",
    startDate: new Date().toISOString().split("T")[0], // Today's date in YYYY-MM-DD format
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<Calendar | null>(null);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Reset states
    setError(null);
    setSuccess(null);
    setIsLoading(true);

    try {
      // Create calendar object (id will be generated by backend)
      const calendarData: Omit<Calendar, "id"> = {
        name: formData.name,
        startDate: new Date(formData.startDate),
      };

      // Call API
      const newCalendar = await createCalendar(calendarData as Calendar);

      // Success
      setSuccess(newCalendar);
      setCurrentCalendar(newCalendar); // Set the calendar in App.tsx state
      setFormData({ name: "", startDate: "" }); // Reset form
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to create calendar",
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="mx-auto flex h-full max-w-lg flex-col space-y-4 p-6">
      <div className="flex justify-between">
        <h2 className="text-2xl font-bold">New Calendar</h2>
        <button className="btn btn-ghost" onClick={onBackClick}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="size-5"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3"
            />
          </svg>
        </button>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Calendar Name Input */}
        <div className="form-control">
          <label className="label">
            <span className="label-text">Calendar Name</span>
          </label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            placeholder={'E.g., "Josh\'s Life"'}
            className="input input-bordered w-full"
            required
          />
        </div>

        {/* Start Date Input */}
        <div className="form-control">
          <label className="label">
            <span className="label-text">Start Date</span>
          </label>
          <input
            type="date"
            name="startDate"
            value={formData.startDate}
            onChange={handleInputChange}
            className="input input-bordered w-full"
            required
          />
        </div>

        {/* Submit Button */}
        <button
          type="submit"
          disabled={isLoading || !formData.name || !formData.startDate}
          className="btn btn-primary w-full"
        >
          {isLoading ? "Creating calendar..." : "Create Calendar"}
        </button>
      </form>

      {/* Error Message */}
      {error && (
        <div className="alert alert-error">
          <svg
            className="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <span>{error}</span>
        </div>
      )}

      {/* Success Message */}
      {success && (
        <div className="alert alert-success">
          <svg
            className="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <span>Calendar "{success.name}" created successfully!</span>
        </div>
      )}
    </div>
  );
};

export default CreateCalendar;
